---
title: "Lecture 1"
author: "Seoncheol Park"
date: "3/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Statstics

- **Statistics**: 

  + **Descriptive statistics**: organizing and summarizing sampled data
  
  + **Inferential statstics**: making inferences abouth populations using samples 
  
### Basic terminology

- **Population**: any large collection of objects or individuals (ex. students)

- **Parameter**: any summary number that describes the entire population (ex. mean)

- **Sample**: a representative group drawn from the population

- **Statistics**: any summary number that describes the sample (ex. sample mean)

## Data

| Student | Heart rate | Sex | Height | Exercise preference |
|-|-|-|-|-|
| 1 | 64 | 0 (M) | 168.5 | 2 (Normal) |
| 2 | 58 | 1 (W) | 168.6 | 2 (Normal) |
| 3 | 62 | 1 (W) | 157.1 | 3 (Like) |
| 4 | 66 | 0 (M) | 183.8 | 1 (Dislike) |
| 5 | 64 | 1 (W) | 157.4 | 2 (Normal) |
| 6 | 64 | 0 (M) | 185.6 | 3 (Like) |
| 7 | 94 | 1 (W) | 173.5 | 2 (Normal) |
| 8 | 60 | 1 (W) | 170.7 | 2 (Normal) |
| 9 | 72 | 0 (M) | 185.2 | 2 (Normal) |
| 10 | 58 | 0 (M) | 175.3 | 2 (Normal) |

***

- Data can be divided into two, qualitative data and quantitative data, by characteristics of measurments:

- **Categorical (qualitative) data**: 

  + **Ordinal data**: order is meaningful (ex. preference)
  
  + **Normal data**: order is not meaningful (ex. sex)

- **Quantitative data**:

  + **Continuous data**: values are from an uncountable, continuous interval (ex. height)
  
  + **Discrete data**: values are countable (ex. heart rate)
